language: elixir
env: MIX_ENV=test
elixir:
  - 1.9
otp_release:
  - 21.0

before_install:
  - CC=clang CXX=clang++ make -C c_src

script: mix coveralls.travis
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
